#ifndef COMPILER_TOKEN_H
#define COMPILER_TOKEN_H

#include <stddef.h>

#define TOKEN_LIST \
TOK(TOK_EOF) \
TOK(TOK_ERR) \
TOK(TOK_HASH) \
TOK(TOK_HASH_HASH) \
TOK(TOK_ID) \
TOK(TOK_KW_CHAR) \
TOK(TOK_KW_INT) \
TOK(TOK_KW_SHORT) \
TOK(TOK_KW_LONG) \
TOK(TOK_KW_FLOAT) \
TOK(TOK_KW_DOUBLE) \
TOK(TOK_KW_VOID) \
TOK(TOK_KW_SIGNED) \
TOK(TOK_KW_UNSIGNED) \
TOK(TOK_KW_STATIC) \
TOK(TOK_KW_EXTERN) \
TOK(TOK_KW_AUTO) \
TOK(TOK_WK_CONST) \
TOK(TOK_KW_VOLATILE) \
TOK(TOK_KW_REGISTER) \
TOK(TOK_KW_GOTO) \
TOK(TOK_KW_IF) \
TOK(TOK_KW_ELSE) \
TOK(TOK_KW_SWITCH) \
TOK(TOK_KW_CASE) \
TOK(TOK_KW_DEFAULT) \
TOK(TOK_KW_BREAK) \
TOK(TOK_KW_CONTINUE) \
TOK(TOK_KW_DO) \
TOK(TOK_KW_WHILE) \
TOK(TOK_KW_FOR) \
TOK(TOK_KW_RETURN) \
TOK(TOK_KW_ENUM) \
TOK(TOK_KW_STRUCT) \
TOK(TOK_KW_UNION) \
TOK(TOK_KW_TYPEDEF) \
TOK(TOK_KW_SIZEOF) \
TOK(TOK_KW_INLINE) \
TOK(TOK_KW_RESTRICT) \
TOK(TOK_KW_BOOL) \
TOK(TOK_KW_COMPLEX) \
TOK(TOK_KW_PRAGMA) \
TOK(TOK_NUM_INT) \
TOK(TOK_NUM_FLOAT) \
TOK(TOK_LIT_CHAR) \
TOK(TOK_LIT_STRING) \
TOK(TOK_LPAREN) \
TOK(TOK_RPAREN) \
TOK(TOK_LBRACKET) \
TOK(TOK_RBRACKET) \
TOK(TOK_LBRACE) \
TOK(TOK_RBRACE) \
TOK(TOK_SEMICOLON) \
TOK(TOK_COMMA) \
TOK(TOK_DOT) \
TOK(TOK_ARROW) \
TOK(TOK_QUESTION) \
TOK(TOK_COLON) \
TOK(TOK_ELLIPSIS) \
TOK(TOK_PLUS) \
TOK(TOK_MINUS) \
TOK(TOK_STAR) \
TOK(TOK_SLASH) \
TOK(TOK_MOD) \
TOK(TOK_INC) \
TOK(TOK_DEC) \
TOK(TOK_EQUAL_EQUAL) \
TOK(TOK_NOT_EQUAL) \
TOK(TOK_LESS) \
TOK(TOK_GREATER) \
TOK(TOK_LESS_EQUAL) \
TOK(TOK_GREATER_EQUAL) \
TOK(TOK_LOGICAL_AND) \
TOK(TOK_LOGICAL_OR) \
TOK(TOK_LOGICAL_NOT) \
TOK(TOK_BIT_AND) \
TOK(TOK_BIT_OR) \
TOK(TOK_BIT_XOR) \
TOK(TOK_BIT_NOT) \
TOK(TOK_SHIFT_LEFT) \
TOK(TOK_SHIFT_RIGHT) \
TOK(TOK_ASSIGN) \
TOK(TOK_PLUS_ASSIGN) \
TOK(TOK_MINUS_ASSIGN) \
TOK(TOK_STAR_ASSIGN) \
TOK(TOK_SLASH_ASSIGN) \
TOK(TOK_MOD_ASSIGN) \
TOK(TOK_SHL_ASSIGN) \
TOK(TOK_SHR_ASSIGN) \
TOK(TOK_AND_ASSIGN) \
TOK(TOK_XOR_ASSIGN) \
TOK(TOK_OR_ASSIGN)

typedef struct String String;

typedef enum TokenType{
    #define TOK(name) name,
        TOKEN_LIST
    #undef TOK
} TokenType;

typedef struct Token{
    TokenType type;
    String *lex;
    size_t line;
    size_t col;
} Token;

#endif